### ISSUE TITLE
.gemspec?

### ISSUE THREAD

**Issue by PragTob** [davy/pirate_game#4]
Hi there,

I was looking around for a .gemspec file for dependencies etc. - any specific reason this isn't part of the repo?
Would be nice for development I think.

And also jay and thanks for building something with shoes :-)

Cheers,
Tobi

**Comment by davy** [comment]
We use hoe to help manage and deploy this gem.

Used hoe-bundler to generate a Gemfile c2e8cb60d6bd36c9237a7a9f9a59c0a2e9fca0c5

Does this help?

**Comment by PragTob** [comment]
Oh I don't know hoe - instructions/links to hoe might also have helped. But a Gemfile now is even better - thanks!

It's just confusing for me to see a ruby gem without a .gemspec.

Thanks!
